=== lafirachid/xmeshadc/trunk/tools/xserve/bin/configxml/xserve_config.dtd
<!ELEMENT XServeConfig (XFieldExtractor)+>

<!ELEMENT XFieldExtractor (XFields,XFilter,XDataSinks)>
<!ATTLIST XFieldExtractor name CDATA #REQUIRED>
<!ATTLIST XFieldExtractor order CDATA #REQUIRED>


<!ELEMENT XFields (XField|XBitField|XUnionField)+>
<!ELEMENT XField (XConversion)?>
<!ATTLIST XField name CDATA #REQUIRED>
<!ATTLIST XField byteoffset CDATA #REQUIRED>
<!ATTLIST XField length CDATA #REQUIRED>
<!ATTLIST XField type (byte|char|short|int|long|uint8|uint16|uint32|uint64|string|raw|float|double) #REQUIRED>
<!ATTLIST XField specialtype (nodeid|parentid|boardid) #IMPLIED>

<!ELEMENT XConversion (XConvParam)*>
<!ATTLIST XConversion function CDATA #REQUIRED>
<!ATTLIST XConversion returntype (byte|char|short|int|long|uint8|uint16|uint32|uint64|string|raw|float|double) #REQUIRED>

<!ELEMENT XConvParam EMPTY>
<!ATTLIST XConvParam variablename CDATA #REQUIRED>
<!ATTLIST XConvParam fieldname CDATA #REQUIRED>
<!ATTLIST XConvParam type (byte|char|short|int|long|uint8|uint16|uint32|uint64|string|raw|float|double) #REQUIRED>



<!ELEMENT XBitField (XConversion)?>
<!ATTLIST XBitField name CDATA #REQUIRED>
<!ATTLIST XBitField byteoffset CDATA #REQUIRED>
<!ATTLIST XBitField length CDATA #REQUIRED>
<!ATTLIST XBitField type (byte|char|short|int|long|uint8|uint16|uint32|uint64|string|raw|float|double) #REQUIRED>
<!ATTLIST XBitField specialtype (nodeid|parentid|boardid) #IMPLIED>
<!ATTLIST XBitField mask CDATA #REQUIRED>
<!ATTLIST XBitField shift CDATA #REQUIRED>

<!ELEMENT XUnionField EMPTY>
<!ATTLIST XUnionField name CDATA #REQUIRED>
<!ATTLIST XUnionField type (byte|char|short|int|long|uint8|uint16|uint32|uint64|string|raw|float|double) #REQUIRED>
<!ATTLIST XUnionField optor CDATA #REQUIRED>
<!ATTLIST XUnionField specialtype (nodeid|parentid|boardid) #IMPLIED>
<!ATTLIST XUnionField leftname CDATA #REQUIRED>
<!ATTLIST XUnionField rightname CDATA #REQUIRED>

<!ELEMENT XDataSinks (XDataSink)*>
<!ELEMENT XDataSink (XDSParam)+>
<!ATTLIST XDataSink name CDATA #REQUIRED>

<!ELEMENT XDSParam EMPTY>
<!ATTLIST XDSParam name CDATA #REQUIRED>
<!ATTLIST XDSParam value CDATA #REQUIRED>


<!ELEMENT XFilter (XCondAnd|XCondOr|XCondNot|XCond)+>
<!ELEMENT XCondAnd (XCondAnd|XCondOr|XCondNot|XCond)+>
<!ELEMENT XCondOr (XCondAnd|XCondOr|XCondNot|XCond)+>
<!ELEMENT XCondNot (XCondAnd|XCondOr|XCondNot|XCond)>
<!ELEMENT XCond (XFilterParam)*>
<!ATTLIST XCond name CDATA #REQUIRED>

<!ELEMENT XFilterParam EMPTY>
<!ATTLIST XFilterParam name CDATA #REQUIRED>
<!ATTLIST XFilterParam value CDATA #REQUIRED>

=== lafirachid/xmeshadc/tools/xserve/bin/configxml/mts310_mesh_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE XServeConfig SYSTEM "./xserve_config.dtd">
<XServeConfig>
	<XFieldExtractor name="XMTS310 Multihop Config XML" order="3">
		<XFields>
			<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
			<XField name="nodeid" byteoffset="7" length="2" type="uint16" specialtype="nodeid"/>
			<XField name="parent" byteoffset="14" length="2" type="uint16" specialtype="parentid"/>
			<XField name="group" byteoffset="3" length="1" type="uint8"/>
			<XField name="socketid" byteoffset="11" length="1" type="uint8"/>
			<XField name="board_id" byteoffset="12" length="1" type="uint8" specialtype="boardid"/>
			<XField name="packet_id" byteoffset="13" length="1" type="uint8"/>
			<XField name="voltage" byteoffset="16" length="2" type="uint16">
				<XConversion function="(1252352/x)" returntype="uint16">
					<XConvParam variablename="x" fieldname="voltage" type="float"/>
				</XConversion>
			</XField>
			<XField name="temp" byteoffset="18" length="2" type="uint16">
				<XConversion function="((1/(.001307050 + 0.000214381 * log( (10000 * (1023-x))/x   ) + 0.000000093 * (log( (10000 * (1023-x))/x )^3))) - 273.15)" returntype="float">
					<XConvParam variablename="x" fieldname="temp" type="uint16"/>					
				</XConversion>			
			</XField>
			<XField name="light" byteoffset="20" length="2" type="uint16">
				<XConversion function="(y * (1252352/x) / 1023)" returntype="uint16">
					<XConvParam variablename="x" fieldname="voltage" type="float"/>
					<XConvParam variablename="y" fieldname="light" type="uint16"/>
				</XConversion>
			</XField>
			<XField name="mic" byteoffset="22" length="2" type="uint16"/>
			<XField name="accel_x" byteoffset="24" length="2" type="uint16">
				<XConversion function="1000.0 * (1.0 - (500 - x)/((500 - 400)/2))" returntype="float">
					<XConvParam variablename="x" fieldname="accel_x" type="uint16"/>					
				</XConversion>

			</XField>
			<XField name="accel_y" byteoffset="26" length="2" type="uint16">
				<XConversion function="1000.0 * (1.0 - (500 - x)/((500 - 400)/2))" returntype="float">
					<XConvParam variablename="x" fieldname="accel_y" type="uint16"/>					
				</XConversion>
			</XField>
			<XField name="mag_x" byteoffset="28" length="2" type="uint16">
				<XConversion function="x / (1.023*2.262*3.2)" returntype="float">
					<XConvParam variablename="x" fieldname="mag_x" type="uint16"/>					
				</XConversion>
			</XField>
			<XField name="mag_y" byteoffset="30" length="2" type="uint16">			
				<XConversion function="x / (1.023*2.262*3.2)" returntype="float">
					<XConvParam variablename="x" fieldname="mag_y" type="uint16"/>					
				</XConversion>
			</XField>
		</XFields>
		<XFilter>
			<XCondAnd>
			
				<!--
					Check if this is a sensor type packet...AMTYPE_MULTIHOP or AMTYPE_XDEBUG
					The Byte offsets defined above assume that there is a multihop header
				/-->
				<XCondOr>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x31"/>
					</XCond>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x33"/>
					</XCond>
					<XCondAnd>
						<XCondOr>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="socketid"/>
								<XFilterParam name="fieldvalue" value="0x31"/>
							</XCond>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="socketid"/>
								<XFilterParam name="fieldvalue" value="0x33"/>
							</XCond>
						</XCondOr>
						<XCondOr>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="amtype"/>
								<XFilterParam name="fieldvalue" value="0x0B"/>
							</XCond>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="amtype"/>
								<XFilterParam name="fieldvalue" value="0x0D"/>
							</XCond>
						</XCondOr>										
					</XCondAnd>
				</XCondOr>
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="board_id"/>
					<XFilterParam name="fieldvalue" value="0x84"/>
				</XCond>				
			</XCondAnd>
		</XFilter>
		<XDataSinks>
			<XDataSink name="Generic Print Datasink">
				<XDSParam name="printstring" value="MTS310 [sensor data converted to engineering units]:\n   health:     node id=%s parent=%s\n   battery:  = %s mv \n   temperature=%s degC\n   light: = %s ADC mv\n   mic: = %s ADC counts\n   AccelX: = %s milliG, AccelY: = %s milliG\n   MagX: = %s mgauss, MagY: =%s mgauss "/>
				<XDSParam name="printfields" value="nodeid,parent,voltage,temp,light,mic,accel_x,accel_y,mag_x,mag_y"/>
			</XDataSink>
			<XDataSink name="Open Log Datasink">
				<XDSParam name="tablename_1" value="mts310_results"/>
				<XDSParam name="createsql_1" value="CREATE TABLE mts310_results ( result_time timestamp without time zone, epoch integer, nodeid integer, parent integer, voltage integer, temp integer, light integer, accel_x integer, accel_y integer, mag_x integer, mag_y integer, mic integer)"/>	
				<XDSParam name="tablename_2" value="mts310_results_l"/>				
				<XDSParam name="createsql_2" value="CREATE TABLE mts310_results_l ( result_time timestamp without time zone, epoch integer, nodeid integer, parent integer, voltage integer, temp integer, light integer, accel_x integer, accel_y integer, mag_x integer, mag_y integer, mic integer)"/>	
				<XDSParam name="rulesql_2" value="CREATE RULE cache_mts310_results AS ON INSERT TO mts310_results DO ( DELETE FROM mts310_results_l WHERE nodeid = NEW.nodeid;INSERT INTO mts310_results_l VALUES (NEW.*); )"/>				
				<XDSParam name="insertsql_2" value="INSERT into mts310_results (result_time,nodeid,parent,voltage,temp,light,accel_x,accel_y,mag_x,mag_y,mic) values (now(),%i,%i,%i,%i,%i,%i,%i,%i,%i,%i)"/>
				<XDSParam name="insertfields_2" value="nodeid,parent,voltage,temp,light,accel_x,accel_y,mag_x,mag_y,mic"/>
			</XDataSink>
			<XDataSink name="Generic Alert Datasink">
				<XDSParam name="voltage" value="[2500,3500]"/>
				<XDSParam name="temp" value="[-5,45]"/>
				<XDSParam name="light" value="[0,3000]"/>
				<XDSParam name="mic" value="[0,800]"/>
				<XDSParam name="accel_x" value="[-2000,2000]"/>
				<XDSParam name="accel_y" value="[-2000,2000]"/>
				<XDSParam name="mag_x" value="[0,100]"/>
				<XDSParam name="mag_y" value="[0,100]"/>
			</XDataSink>
			<XDataSink name="Generic Modbus Datasink">
				<XDSParam name="Mapping1" value="1,voltage,0"/>
				<XDSParam name="Mapping2" value="2,temp,0"/>	
				<XDSParam name="Mapping3" value="3,light,0"/>	
				<XDSParam name="Mapping4" value="4,accel_x,0"/>	
				<XDSParam name="Mapping5" value="5,accel_y,0"/>	
				<XDSParam name="Mapping6" value="6,mag_x,0"/>	
				<XDSParam name="Mapping7" value="7,mag_y,0"/>					
				<XDSParam name="Mapping8" value="8,mic,0"/>
				<XDSParam name="Mapping9" value="9,voltage,1"/>
				<XDSParam name="Mapping10" value="10,temp,1"/>	
				<XDSParam name="Mapping11" value="11,light,1"/>	
				<XDSParam name="Mapping12" value="12,accel_x,1"/>	
				<XDSParam name="Mapping13" value="13,accel_y,1"/>	
				<XDSParam name="Mapping14" value="14,mag_x,1"/>	
				<XDSParam name="Mapping15" value="15,mag_y,1"/>	
				<XDSParam name="Mapping16" value="16,mic,1"/>																				
			</XDataSink>				
		</XDataSinks>
	</XFieldExtractor>
	
</XServeConfig>

=== lafirachid/xmeshadc/trunk/tools/xserve/bin/configxml/mda500_sensor_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE XServeConfig SYSTEM "./xserve_config.dtd">
<XServeConfig>
	<XFieldExtractor name="XMDA500 Sensor Config XML" order="3">
		<XFields>
			<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
			<XField name="nodeid" byteoffset="7" length="2" type="uint16" specialtype="nodeid"/>
			<!--
			<XField name="parent" byteoffset="14" length="2" type="uint16" specialtype="parentid"/>
			/-->
			<XField name="group" byteoffset="3" length="1" type="uint8"/>
			<XField name="board_id" byteoffset="5" length="1" type="uint8" specialtype="boardid"/>
			<XField name="packet_id" byteoffset="6" length="1" type="uint8"/>
			<XField name="voltage" byteoffset="9" length="2" type="uint16">
				<XConversion function="(1251100/x)" returntype="uint16">
					<XConvParam variablename="x" fieldname="voltage" type="float"/>
				</XConversion>
			</XField>
			<XField name="tempR" byteoffset="11" length="2" type="uint16">
				<XConversion function="(10000*x / (1023-x))" returntype="uint16">
					<XConvParam variablename="x" fieldname="tempR" type="uint16"/>					
				</XConversion>			
			</XField>
			<XField name="temp" byteoffset="13" length="2" type="uint16">
				<XConversion function="((1/(.001307050 + 0.000214381 * log( (10000 *x/ (1023-x))   ) + 0.000000093 * (log( (10000 *x/ (1023-x)) )^3))) - 273.15)" returntype="float">
					<XConvParam variablename="x" fieldname="temp" type="uint16"/>					
				</XConversion>			
			</XField>
			<XField name="adc2" byteoffset="15" length="2" type="uint16">
				<XConversion function="(x*1251100/(1023*y))" returntype="uint16">
					<XConvParam variablename="x" fieldname="adc2" type="float"/>					
					<XConvParam variablename="y" fieldname="voltage" type="float"/>				
				</XConversion>			
			</XField>
			<XField name="adc3" byteoffset="17" length="2" type="uint16">
				<XConversion function="(x*1251100/(1023*y))" returntype="uint16">
					<XConvParam variablename="x" fieldname="adc3" type="float"/>					
					<XConvParam variablename="y" fieldname="voltage" type="float"/>				
				</XConversion>			
			</XField>
			<XField name="adc4" byteoffset="19" length="2" type="uint16">
				<XConversion function="(x*1251100/(1023*y))" returntype="uint16">
					<XConvParam variablename="x" fieldname="adc4" type="float"/>					
					<XConvParam variablename="y" fieldname="voltage" type="float"/>				
				</XConversion>			
			</XField>
			<XField name="adc5" byteoffset="21" length="2" type="uint16">
				<XConversion function="(x*1251100/(1023*y))" returntype="uint16">
					<XConvParam variablename="x" fieldname="adc5" type="float"/>					
					<XConvParam variablename="y" fieldname="voltage" type="float"/>				
				</XConversion>			
			</XField>
			<XField name="adc6" byteoffset="23" length="2" type="uint16">
				<XConversion function="(x*1251100/(1023*y))" returntype="uint16">
					<XConvParam variablename="x" fieldname="adc6" type="float"/>					
					<XConvParam variablename="y" fieldname="voltage" type="float"/>				
				</XConversion>			
			</XField>
			<XField name="adc7" byteoffset="25" length="2" type="uint16">
				<XConversion function="(x*1251100/(1023*y))" returntype="uint16">
					<XConvParam variablename="x" fieldname="adc7" type="float"/>					
					<XConvParam variablename="y" fieldname="voltage" type="float"/>				
				</XConversion>			
			</XField>
		</XFields>
		<XFilter>
			<XCondAnd>
			
				<!--
					Check if this is a sensor type packet...AMTYPE_MULTIHOP or AMTYPE_XDEBUG
					The Byte offsets defined above assume that there is a multihop header
				/-->
				<XCondOr>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x00"/>
					</XCond>

					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x32"/>
					</XCond>

				</XCondOr>
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="board_id"/>
					<XFilterParam name="fieldvalue" value="0x01"/>
				</XCond>				
			</XCondAnd>
		</XFilter>
		<XDataSinks>
			<XDataSink name="Generic Print Datasink">
				<XDSParam name="printstring" value="MDA500 [sensor data converted to engineering units]:\n   health:     node id=%s\n   battery:    volts=%s mv\n   thermistor: resistance=%s ohms, tempurature=%s C\n   adc chan 2: voltage=%s mv\n   adc chan 3: voltage=%s mv\n   adc chan 4: voltage=%s mv\n   adc chan 5: voltage=%s mv\n   adc chan 6: voltage=%s mv\n   adc chan 7: voltage=%s mv "/>
				<XDSParam name="printfields" value="nodeid,voltage,tempR,temp,adc2,adc3,adc4,adc5,adc6,adc7"/>
			</XDataSink>
			<XDataSink name="Open Log Datasink">
				<XDSParam name="tablename_1" value="mda500_results"/>
				<XDSParam name="createsql_1" value="CREATE TABLE mda500_results ( result_time timestamp without time zone,epoch integer, nodeid integer, parent integer,voltage integer, temp integer, adc2 integer,adc3 integer, adc4 integer, adc5 integer, adc6 integer, adc7 integer)"/>				
				<XDSParam name="tablename_2" value="mda500_results_l"/>				
				<XDSParam name="createsql_2" value="CREATE TABLE mda500_results_l ( result_time timestamp without time zone,epoch integer, nodeid integer, parent integer,voltage integer, temp integer, adc2 integer,adc3 integer, adc4 integer, adc5 integer, adc6 integer, adc7 integer)"/>
				<XDSParam name="rulesql_2" value="CREATE RULE cache_mda500_results AS ON INSERT TO mda500_results DO ( DELETE FROM mda500_results_l WHERE nodeid = NEW.nodeid;INSERT INTO mda500_results_l VALUES (NEW.*); )"/>				
				<XDSParam name="insertsql_2" value="INSERT into mda500_results (result_time,nodeid,voltage,temp,adc2,adc3,adc4,adc5,adc6,adc7)values (now(),%i,%i,%i,%i,%i,%i,%i,%i,%i)"/>
				<XDSParam name="insertfields_2" value="nodeid,voltage,temp,adc2,adc3,adc4,adc5,adc6,adc7"/>
			</XDataSink>
			<XDataSink name="Generic Alert Datasink">
				<XDSParam name="voltage" value="[2500,3500]"/>
				<XDSParam name="temp" value="[-5,45]"/>
				<XDSParam name="adc2" value="[0,3200]"/>
				<XDSParam name="adc3" value="[0,3200]"/>
				<XDSParam name="adc4" value="[0,3200]"/>
				<XDSParam name="adc5" value="[0,3200]"/>
				<XDSParam name="adc6" value="[0,3200]"/>
				<XDSParam name="adc7" value="[0,3200]"/>
			</XDataSink>
		</XDataSinks>
	</XFieldExtractor>

</XServeConfig>

=== lafirachid/xmeshadc/trunk/tools/xserve/bin/configxml/msp410_mesh_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE XServeConfig SYSTEM "./xserve_config.dtd">
<XServeConfig>
	<XFieldExtractor name="XMSP410 Multihop PK1 Config XML" order="3">
		<XFields>
			<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
			<XField name="nodeid" byteoffset="7" length="2" type="uint16" specialtype="nodeid"/>
			<XField name="parent" byteoffset="14" length="2" type="uint16" specialtype="parentid"/>
			<XField name="group" byteoffset="3" length="1" type="uint8"/>
			<XField name="socketid" byteoffset="11" length="1" type="uint8"/>
			<XField name="board_id" byteoffset="12" length="1" type="uint8" specialtype="boardid"/>
			<XField name="packet_id" byteoffset="13" length="1" type="uint8"/>
			<XField name="seqno" byteoffset="16" length="2" type="uint16"/>
			<XField name="voltage" byteoffset="18" length="1" type="uint8">
				<XConversion function="(1252352/(2*x))" returntype="uint16">
					<XConvParam variablename="x" fieldname="voltage" type="float"/>
				</XConversion>
			</XField>
			<XField name="quad" byteoffset="19" length="1" type="uint8"/>
			<XField name="pir" byteoffset="20" length="2" type="uint16"/>
			<XField name="mag" byteoffset="22" length="2" type="uint16"/>
			<XField name="audio" byteoffset="24" length="2" type="uint16"/>
		</XFields>
		<XFilter>
			<XCondAnd>
			
				<!--
					Check if this is a sensor type packet...AMTYPE_MULTIHOP or AMTYPE_XDEBUG
					The Byte offsets defined above assume that there is a multihop header
				/-->
				<XCondOr>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x31"/>
					</XCond>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x33"/>
					</XCond>
					<XCondAnd>
						<XCondOr>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="socketid"/>
								<XFilterParam name="fieldvalue" value="0x31"/>
							</XCond>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="socketid"/>
								<XFilterParam name="fieldvalue" value="0x33"/>
							</XCond>
						</XCondOr>
						<XCondOr>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="amtype"/>
								<XFilterParam name="fieldvalue" value="0x0B"/>
							</XCond>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="amtype"/>
								<XFilterParam name="fieldvalue" value="0x0D"/>
							</XCond>
						</XCondOr>
					
					</XCondAnd>
				</XCondOr>
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="board_id"/>
					<XFilterParam name="fieldvalue" value="0xA0"/>
				</XCond>				
				<XCondOr>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="packet_id"/>
						<XFilterParam name="fieldvalue" value="0x81"/>
					</XCond>

					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="packet_id"/>
						<XFilterParam name="fieldvalue" value="0x01"/>
					</XCond>
				</XCondOr>
			</XCondAnd>
		</XFilter>
		<XDataSinks>
			<XDataSink name="Generic Print Datasink">
				<XDSParam name="printstring" value="MSP410 [sensor data converted to engineering units]:\n   health:     node id=%s parent=%s seq=%s\n   battery:  = %s mv \n   quad:     = %s ADC\n   pir:      = %s ADC\n   mic:      = %s ADC\n   Mag:      = %s ADC"/>
				<XDSParam name="printfields" value="nodeid,parent,seqno,voltage,quad,pir,audio,mag"/>
			</XDataSink>
			<XDataSink name="Open Log Datasink">
				<XDSParam name="tablename_1" value="msp410_results"/>
				<XDSParam name="createsql_1" value="CREATE TABLE msp410_results ( result_time timestamp without time zone, epoch integer, nodeid integer, parent integer, voltage integer, quad integer, pir integer, audio integer, mag integer )"/>				
				<XDSParam name="tablename_2" value="msp410_results_l"/>				
				<XDSParam name="createsql_2" value="CREATE TABLE msp410_results_l ( result_time timestamp without time zone, epoch integer, nodeid integer, parent integer, voltage integer, quad integer, pir integer, audio integer, mag integer )"/>
				<XDSParam name="rulesql_2" value="CREATE RULE cache_msp410_results AS ON INSERT TO msp410_results DO ( DELETE FROM msp410_results_l WHERE nodeid = NEW.nodeid;INSERT INTO msp410_results_l VALUES (NEW.*); )"/>				
				<XDSParam name="insertsql_2" value="INSERT into msp410_results (result_time,epoch,nodeid,parent,voltage,quad,pir,audio,mag) values (now(),%i,%i,%i,%i,%i,%i,%i,%i)"/>
				<XDSParam name="insertfields_2" value="seqno,nodeid,parent,voltage,quad,pir,audio,mag"/>
			</XDataSink>
		</XDataSinks>
	</XFieldExtractor>

</XServeConfig>

=== lafirachid/xmeshadc/trunk/apps/xmesh/XMTS410/mts410_mesh_config_debug.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- This class is automatically generated by mig. DO NOT EDIT THIS FILE. -->
<!-- $Id: mts410_mesh_config_debug.xml,v 1.1.2.1 2007/02/02 02:25:01 nxu Exp $ -->
<!DOCTYPE XServeConfig SYSTEM "./xserve_config.dtd">
<XServeConfig>
<XFieldExtractor name="XDataMsg XServe Config XML" order="1">
  <XFields>

	<XField name="addr" byteoffset="0" length="2" type="uint16"/>
	<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
	<XField name="groupid" byteoffset="3" length="1" type="uint8"/>
	<XField name="length" byteoffset="4" length="1" type="uint8"/>
	<XField name="sourceaddr" byteoffset="5" length="2" type="uint16"/>
	<XField name="nodeid" byteoffset="7" length="2" type="uint16" specialtype="nodeid"/>
	<XField name="seqno" byteoffset="9" length="2" type="short"/>
	<XField name="socket" byteoffset="11" length="1" type="uint8"/>
	<XField name="board_id" byteoffset="12" length="1" type="uint8" specialtype="boardid"/>
	<XField name="packet_id" byteoffset="13" length="1" type="uint8"/>
	<XField name="parent" byteoffset="14" length="2" type="uint16" specialtype="parentid"/>
	<XField name="seq_no" byteoffset="16" length="2" type="uint16"/>
	<XField name="vref" byteoffset="18" length="2" type="uint16"/>
	<XField name="pir" byteoffset="20" length="1" type="uint8"/>
	<XField name="pir_sum" byteoffset="21" length="1" type="uint8"/>
	<XField name="humidity" byteoffset="22" length="2" type="uint16"/>
	<XField name="temperature" byteoffset="24" length="2" type="uint16"/>
	<XField name="cal_wrod1" byteoffset="26" length="2" type="uint16"/>
	<XField name="cal_wrod2" byteoffset="28" length="2" type="uint16"/>
	<XField name="cal_wrod3" byteoffset="30" length="2" type="uint16"/>
	<XField name="cal_wrod4" byteoffset="32" length="2" type="uint16"/>
	<XField name="intersematemp" byteoffset="34" length="2" type="uint16"/>
	<XField name="pressure" byteoffset="36" length="2" type="uint16"/>
	<XField name="accelx" byteoffset="38" length="2" type="uint16"/>
	<XField name="accely" byteoffset="40" length="2" type="uint16"/>
	<XField name="taoch0" byteoffset="42" length="2" type="uint16"/>
	<XField name="taoch1" byteoffset="44" length="2" type="uint16"/>
	<XField name="audio" byteoffset="46" length="2" type="uint16"/>
	<XField name="adc5" byteoffset="48" length="2" type="uint16"/>
	<XField name="adc6" byteoffset="50" length="2" type="uint16"/>
	<XField name="pir_max" byteoffset="52" length="2" type="uint16"/>
	<XField name="pir_bias" byteoffset="16" length="2" type="uint16"/>
	<XField name="pir_threshold" byteoffset="18" length="2" type="uint16"/>
	<XField name="pir_N" byteoffset="20" length="2" type="uint16"/>
	<XField name="pir_T" byteoffset="22" length="2" type="uint16"/>
  </XFields>
  <XFilter>  <XCond name="alwaysTrue"/>  </XFilter>
<XDataSinks>
   <XDataSink name="Generic Print Datasink">
		<XDSParam name="printstring" 
				   value="XDataMsg:\n
      addr = 	%s\n
      amtype = 	%s\n
      groupid = 	%s\n
      length = 	%s\n
      sourceaddr = 	%s\n
      nodeid = 	%s\n
      seqno = 	%s\n
      socket = 	%s\n
      board_id = 	%s\n
      packet_id = 	%s\n
      parent = 	%s\n
      seq_no = 	%s\n
      vref = 	%s\n
      pir = 	%s\n
      pir_sum = 	%s\n
      humidity = 	%s\n
      temperature = 	%s\n
      cal_wrod1 = 	%s\n
      cal_wrod2 = 	%s\n
      cal_wrod3 = 	%s\n
      cal_wrod4 = 	%s\n
      intersematemp = 	%s\n
      pressure = 	%s\n
      accelx = 	%s\n
      accely = 	%s\n
      taoch0 = 	%s\n
      taoch1 = 	%s\n
      audio = 	%s\n
      adc5 = 	%s\n
      adc6 = 	%s\n
      pir_max = 	%s\n
      pir_bias = 	%s\n
      pir_threshold = 	%s\n
      pir_N = 	%s\n
      pir_T = 	%s\n
"/>
		<XDSParam name="printfields" value="addr,amtype,groupid,length,sourceaddr,nodeid,seqno,socket,board_id,packet_id,parent,seq_no,vref,pir,pir_sum,humidity,temperature,cal_wrod1,cal_wrod2,cal_wrod3,cal_wrod4,intersematemp,pressure,accelx,accely,taoch0,taoch1,audio,adc5,adc6,pir_max,pir_bias,pir_threshold,pir_N,pir_T"/>
   </XDataSink>
   <XDataSink name="Generic File Datasink">                      
     <XDSParam name="rawfilename" value="XDataMsg_raw.txt"/>
     <XDSParam name="parsedfilename" value="XDataMsg_parsed.txt"/>
     <XDSParam name="convertedfilename" value="XDataMsg_converted.txt"/>        
     <XDSParam name="delim" value=","/>
     <XDSParam name="header" value="yes"/>
     <XDSParam name="timestamp" value="%m-%d-%Y %H:%M:%S"/>
     <XDSParam name="backup" value="yes"/>
   </XDataSink>
	<XDataSink name="Open Log Datasink">
		<XDSParam name="tablename_1" value="mts410_results"/>
		<XDSParam name="createsql_1" value=
		   "DELETE FROM task_query_log where query_id=162;
			INSERT INTO task_query_log (query_id, table_name, query_type) VALUES (162, 'mts410_results', 'MOTEVIEW_1_0');
			CREATE TABLE mts410_results ( result_time timestamp without time zone, nodeid integer,parent integer,vref integer,pir integer,pir_sum integer,pir_max integer,humidity integer,temperature integer); 
		CREATE INDEX XDataMsg_time_idx ON mts410_results USING BTREE ( result_time ) ;
		CREATE INDEX XDataMsg_nodeid_idx ON mts410_results USING BTREE ( nodeid ) ;"/>	
		<XDSParam name="tablename_2" value="mts410_results_l"/>				
		<XDSParam name="createsql_2" value="CREATE TABLE mts410_results_l ( result_time timestamp without time zone, nodeid integer,parent integer,vref integer,pir integer,pir_sum integer,pir_max integer,humidity integer,temperature integer)"/>
		<XDSParam name="rulesql_2" value="CREATE RULE XDataMsg_cache_results AS ON INSERT TO mts410_results DO ( DELETE FROM mts410_results_l WHERE nodeid = NEW.nodeid;INSERT INTO mts410_results_l VALUES (NEW.*); )"/>				
		<XDSParam name="insertsql_2" value="INSERT into mts410_results (result_time , nodeid ,parent ,vref ,pir ,pir_sum ,pir_max ,humidity ,temperature ) values (now(),%i,%i,%i,%i,%i,%i,%i,%i)"/>
		<XDSParam name="insertfields_2" value="nodeid,parent,vref,pir,pir_sum,pir_max,humidity,temperature"/>
	</XDataSink>
</XDataSinks>
</XFieldExtractor>
</XServeConfig>
<!-- This class is automatically generated by mig. DO NOT EDIT THIS FILE. -->
