=== lafirachid/xmeshadc/trunk/tools/xserve/bin/configxml/xserve_config.dtd
<!ELEMENT XServeConfig (XFieldExtractor)+>

<!ELEMENT XFieldExtractor (XFields,XFilter,XDataSinks)>
<!ATTLIST XFieldExtractor name CDATA #REQUIRED>
<!ATTLIST XFieldExtractor order CDATA #REQUIRED>


<!ELEMENT XFields (XField|XBitField|XUnionField)+>
<!ELEMENT XField (XConversion)?>
<!ATTLIST XField name CDATA #REQUIRED>
<!ATTLIST XField byteoffset CDATA #REQUIRED>
<!ATTLIST XField length CDATA #REQUIRED>
<!ATTLIST XField type (byte|char|short|int|long|uint8|uint16|uint32|uint64|string|raw|float|double) #REQUIRED>
<!ATTLIST XField specialtype (nodeid|parentid|boardid) #IMPLIED>

<!ELEMENT XConversion (XConvParam)*>
<!ATTLIST XConversion function CDATA #REQUIRED>
<!ATTLIST XConversion returntype (byte|char|short|int|long|uint8|uint16|uint32|uint64|string|raw|float|double) #REQUIRED>

<!ELEMENT XConvParam EMPTY>
<!ATTLIST XConvParam variablename CDATA #REQUIRED>
<!ATTLIST XConvParam fieldname CDATA #REQUIRED>
<!ATTLIST XConvParam type (byte|char|short|int|long|uint8|uint16|uint32|uint64|string|raw|float|double) #REQUIRED>



<!ELEMENT XBitField (XConversion)?>
<!ATTLIST XBitField name CDATA #REQUIRED>
<!ATTLIST XBitField byteoffset CDATA #REQUIRED>
<!ATTLIST XBitField length CDATA #REQUIRED>
<!ATTLIST XBitField type (byte|char|short|int|long|uint8|uint16|uint32|uint64|string|raw|float|double) #REQUIRED>
<!ATTLIST XBitField specialtype (nodeid|parentid|boardid) #IMPLIED>
<!ATTLIST XBitField mask CDATA #REQUIRED>
<!ATTLIST XBitField shift CDATA #REQUIRED>

<!ELEMENT XUnionField EMPTY>
<!ATTLIST XUnionField name CDATA #REQUIRED>
<!ATTLIST XUnionField type (byte|char|short|int|long|uint8|uint16|uint32|uint64|string|raw|float|double) #REQUIRED>
<!ATTLIST XUnionField optor CDATA #REQUIRED>
<!ATTLIST XUnionField specialtype (nodeid|parentid|boardid) #IMPLIED>
<!ATTLIST XUnionField leftname CDATA #REQUIRED>
<!ATTLIST XUnionField rightname CDATA #REQUIRED>

<!ELEMENT XDataSinks (XDataSink)*>
<!ELEMENT XDataSink (XDSParam)+>
<!ATTLIST XDataSink name CDATA #REQUIRED>

<!ELEMENT XDSParam EMPTY>
<!ATTLIST XDSParam name CDATA #REQUIRED>
<!ATTLIST XDSParam value CDATA #REQUIRED>


<!ELEMENT XFilter (XCondAnd|XCondOr|XCondNot|XCond)+>
<!ELEMENT XCondAnd (XCondAnd|XCondOr|XCondNot|XCond)+>
<!ELEMENT XCondOr (XCondAnd|XCondOr|XCondNot|XCond)+>
<!ELEMENT XCondNot (XCondAnd|XCondOr|XCondNot|XCond)>
<!ELEMENT XCond (XFilterParam)*>
<!ATTLIST XCond name CDATA #REQUIRED>

<!ELEMENT XFilterParam EMPTY>
<!ATTLIST XFilterParam name CDATA #REQUIRED>
<!ATTLIST XFilterParam value CDATA #REQUIRED>

=== lafirachid/xmeshadc/tools/xserve/bin/configxml/mts300_mesh_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE XServeConfig SYSTEM "./xserve_config.dtd">
<XServeConfig>
	<XFieldExtractor name="XMTS300 Multihop Config XML" order="3">
		<XFields>
			<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
			<XField name="nodeid" byteoffset="7" length="2" type="uint16" specialtype="nodeid"/>
			<XField name="parent" byteoffset="14" length="2" type="uint16" specialtype="parentid"/>
			<XField name="group" byteoffset="3" length="1" type="uint8"/>
			<XField name="socketid" byteoffset="11" length="1" type="uint8"/>
			<XField name="board_id" byteoffset="12" length="1" type="uint8" specialtype="boardid"/>
			<XField name="packet_id" byteoffset="13" length="1" type="uint8"/>
			<XField name="voltage" byteoffset="16" length="2" type="uint16">
				<XConversion function="(1252352/x)" returntype="uint16">
					<XConvParam variablename="x" fieldname="voltage" type="float"/>
				</XConversion>
			</XField>
			<XField name="temp" byteoffset="18" length="2" type="uint16">
				<XConversion function="((1/(.001307050 + 0.000214381 * log( (10000 * (1023-x))/x   ) + 0.000000093 * (log( (10000 * (1023-x))/x )^3))) - 273.15)" returntype="float">
					<XConvParam variablename="x" fieldname="temp" type="uint16"/>					
				</XConversion>			
			</XField>
			<XField name="light" byteoffset="20" length="2" type="uint16">
				<XConversion function="(y * (1252352/x) / 1023)" returntype="uint16">
					<XConvParam variablename="x" fieldname="voltage" type="float"/>
					<XConvParam variablename="y" fieldname="light" type="uint16"/>
				</XConversion>
			</XField>
			<XField name="mic" byteoffset="22" length="2" type="uint16"/>
		</XFields>
		<XFilter>
			<XCondAnd>
			
				<!--
					Check if this is a sensor type packet...AMTYPE_MULTIHOP or AMTYPE_XDEBUG
					The Byte offsets defined above assume that there is a multihop header
				/-->
				<XCondOr>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x31"/>
					</XCond>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x33"/>
					</XCond>
					<XCondAnd>
						<XCondOr>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="socketid"/>
								<XFilterParam name="fieldvalue" value="0x31"/>
							</XCond>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="socketid"/>
								<XFilterParam name="fieldvalue" value="0x33"/>
							</XCond>
						</XCondOr>
						<XCondOr>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="amtype"/>
								<XFilterParam name="fieldvalue" value="0x0B"/>
							</XCond>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="amtype"/>
								<XFilterParam name="fieldvalue" value="0x0D"/>
							</XCond>
						</XCondOr>
					
					</XCondAnd>
				</XCondOr>
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="board_id"/>
					<XFilterParam name="fieldvalue" value="0x83"/>
				</XCond>				
			</XCondAnd>
		</XFilter>
		<XDataSinks>
			<XDataSink name="Generic Print Datasink">
				<XDSParam name="printstring" value="MTS300 [sensor data converted to engineering units]:\n   health:     node id=%s parent=%s\n   battery:  = %s mv \n   temperature=%s degC\n   light: = %s ADC mv\n   mic: = %s ADC counts "/>
				<XDSParam name="printfields" value="nodeid,parent,voltage,temp,light,mic"/>
			</XDataSink>
			<XDataSink name="Generic Alert Datasink">
				<XDSParam name="voltage" value="[2500,3500]"/>
				<XDSParam name="temp" value="[-5,45]"/>
				<XDSParam name="light" value="[0,3000]"/>
				<XDSParam name="mic" value="[0,1000]"/>
			</XDataSink>
			<XDataSink name="Open Log Datasink">
				<XDSParam name="tablename_1" value="mts300_results"/>
				<XDSParam name="createsql_1" value="CREATE TABLE mts300_results ( result_time timestamp without time zone,epoch integer, nodeid integer, parent integer,voltage integer, temp integer, light integer, mic integer)"/>				
				<XDSParam name="tablename_2" value="mts300_results_l"/>				
				<XDSParam name="createsql_2" value="CREATE TABLE mts300_results_l ( result_time timestamp without time zone,epoch integer, nodeid integer, parent integer,voltage integer, temp integer, light integer, mic integer)"/>
				<XDSParam name="rulesql_2" value="CREATE RULE cache_mts300_results AS ON INSERT TO mts300_results DO ( DELETE FROM mts300_results_l WHERE nodeid = NEW.nodeid;INSERT INTO mts300_results_l VALUES (NEW.*); )"/>				
				<XDSParam name="insertsql_2" value="INSERT into mts300_results (result_time,nodeid,parent,voltage,temp,light,mic) values (now(),%i,%i,%i,%i,%i,%i)"/>
				<XDSParam name="insertfields_2" value="nodeid,parent,voltage,temp,light,mic"/>
			</XDataSink>
		</XDataSinks>
	</XFieldExtractor>

</XServeConfig>

=== lafirachid/xmeshadc/tools/xserve/bin/configxml/tpr2400_mesh_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE XServeConfig SYSTEM "./xserve_config.dtd">
<XServeConfig>
	<XFieldExtractor name="XMDA100 Multihop Config XML" order="3">
		<XFields>
			<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
			<XField name="nodeid" byteoffset="7" length="2" type="uint16" specialtype="nodeid"/>
			<XField name="parent" byteoffset="14" length="2" type="uint16" specialtype="parentid"/>
			<XField name="group" byteoffset="3" length="1" type="uint8"/>
			<XField name="socketid" byteoffset="11" length="1" type="uint8"/>
			<XField name="board_id" byteoffset="12" length="1" type="uint8" specialtype="boardid"/>
			<XField name="packet_id" byteoffset="13" length="1" type="uint8"/>
			<XField name="voltage" byteoffset="16" length="2" type="uint16">
				<XConversion function="(3000*x/4096)" returntype="uint16">
					<XConvParam variablename="x" fieldname="voltage" type="float"/>
				</XConversion>
			</XField>
			<XField name="intemp" byteoffset="18" length="2" type="uint16"/>
			<XField name="humidity" byteoffset="20" length="2" type="uint16">
				<XConversion function="(-38.4 + 0.0098*y - 25.0)*(0.01 + 0.00008 * x) - 4.0 + 0.0405 * x - 0.0000028 * x * x" returntype="uint16">
					<XConvParam variablename="x" fieldname="humidity" type="float"/>					
					<XConvParam variablename="y" fieldname="humtemp" type="float"/>				
				</XConversion>			
			</XField>
			<XField name="humtemp" byteoffset="22" length="2" type="uint16">
				<XConversion function="(-38.4 + 0.0098*x)" returntype="uint16">
					<XConvParam variablename="x" fieldname="humtemp" type="float"/>					
				</XConversion>			
			</XField>
			<XField name="tsrdata" byteoffset="24" length="2" type="uint16">
				<XConversion function="(3000*x/4096)*y/4096" returntype="uint16">
					<XConvParam variablename="x" fieldname="tsrdata" type="float"/>					
					<XConvParam variablename="y" fieldname="voltage" type="float"/>					
				</XConversion>			
			</XField>
			<XField name="pardata" byteoffset="26" length="2" type="uint16">
				<XConversion function="(3000*x/4096)*y/4096" returntype="uint16">
					<XConvParam variablename="x" fieldname="pardata" type="float"/>					
					<XConvParam variablename="y" fieldname="voltage" type="float"/>					
				</XConversion>			
			</XField>
		</XFields>
		<XFilter>
			<XCondAnd>
			
				<!--
					Check if this is a sensor type packet...AMTYPE_MULTIHOP or AMTYPE_XDEBUG
					The Byte offsets defined above assume that there is a multihop header
				/-->
				<XCondOr>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x31"/>
					</XCond>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x33"/>
					</XCond>
					<XCondAnd>
						<XCondOr>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="socketid"/>
								<XFilterParam name="fieldvalue" value="0x31"/>
							</XCond>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="socketid"/>
								<XFilterParam name="fieldvalue" value="0x33"/>
							</XCond>
						</XCondOr>
						<XCondOr>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="amtype"/>
								<XFilterParam name="fieldvalue" value="0x0B"/>
							</XCond>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="amtype"/>
								<XFilterParam name="fieldvalue" value="0x0D"/>
							</XCond>
						</XCondOr>
					
					</XCondAnd>
				</XCondOr>
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="board_id"/>
					<XFilterParam name="fieldvalue" value="0x40"/>
				</XCond>				
			</XCondAnd>
		</XFilter>
		<XDataSinks>
			<XDataSink name="Generic Print Datasink">
				<XDSParam name="printstring" value="TPR2400 [sensor data converted to engineering units]:\n	health:	node id	= %s\n	battery:	= %s mv \n	humidity:	= %f%% \n	temp:		= %f degC \n	PAR:		= %s mv \n	TSR:		= %s mv "/>
				<XDSParam name="printfields" value="nodeid,voltage,humidity,humtemp,pardata,tsrdata"/>
			</XDataSink>
			<XDataSink name="Open Log Datasink">
				<XDSParam name="tablename_1" value="tpr2400_results"/>
				<XDSParam name="createsql_1" value="CREATE TABLE tpr2400_results ( result_time timestamp without time zone,epoch integer, nodeid integer, parent integer,voltage integer, intemp integer, humidity integer, humtemp integer,tsrdata integer, pardata integer )"/>				
				<XDSParam name="tablename_2" value="tpr2400_results_l"/>				
				<XDSParam name="createsql_2" value="CREATE TABLE tpr2400_results_l ( result_time timestamp without time zone,epoch integer, nodeid integer, parent integer,voltage integer, intemp integer, humidity integer, humtemp integer,tsrdata integer, pardata integer )"/>
				<XDSParam name="rulesql_2" value="CREATE RULE cache_tpr2400_results AS ON INSERT TO tpr2400_results DO ( DELETE FROM mda100_results_l WHERE nodeid = NEW.nodeid;INSERT INTO tpr2400_results_l VALUES (NEW.*); )"/>				
				<XDSParam name="insertsql_2" value="INSERT into tpr2400_results (result_time,nodeid,voltage,intemp,humidity,humtemp,tsrdata,pardata) values (now(),%i,%i,%i,%i,%i,%i,%i)"/>
				<XDSParam name="insertfields_2" value="nodeid,voltage,intemp,humidity,humtemp,pardata,tsrdata"/>
			</XDataSink>
		</XDataSinks>
	</XFieldExtractor>

</XServeConfig>

=== lafirachid/xmeshadc/tools/xserve/bin/configxml/mts101_sensor_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE XServeConfig SYSTEM "./xserve_config.dtd">
<XServeConfig>
	<XFieldExtractor name="XMTS101 Sensor Config XML" order="3">
		<XFields>
			<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
			<XField name="nodeid" byteoffset="7" length="2" type="uint16" specialtype="nodeid"/>
			<!--
			<XField name="parent" byteoffset="14" length="2" type="uint16" specialtype="parentid"/>
			/-->
			<XField name="group" byteoffset="3" length="1" type="uint8"/>
			<XField name="board_id" byteoffset="5" length="1" type="uint8" specialtype="boardid"/>
			<XField name="packet_id" byteoffset="6" length="1" type="uint8"/>
			<XField name="voltage" byteoffset="9" length="2" type="uint16">
				<XConversion function="(1252352/x)" returntype="uint16">
					<XConvParam variablename="x" fieldname="voltage" type="float"/>
				</XConversion>
			</XField>
			<XField name="temp" byteoffset="11" length="2" type="uint16">
				<XConversion function="((1/(.001307050 + 0.000214381 * log( (10000 * (1023-x))/x   ) + 0.000000093 * (log( (10000 * (1023-x))/x )^3))) - 273.15)" returntype="float">
					<XConvParam variablename="x" fieldname="temp" type="uint16"/>					
				</XConversion>			
			</XField>
			<XField name="light" byteoffset="13" length="2" type="uint16">
				<XConversion function="(y * (1252352/x) / 1023)" returntype="uint16">
					<XConvParam variablename="x" fieldname="voltage" type="float"/>
					<XConvParam variablename="y" fieldname="light" type="uint16"/>
				</XConversion>
			</XField>
			<XField name="adc0" byteoffset="15" length="2" type="uint16"/>
			<XField name="adc1" byteoffset="17" length="2" type="uint16"/>
			<XField name="adc2" byteoffset="19" length="2" type="uint16"/>
			<XField name="adc3" byteoffset="21" length="2" type="uint16"/>
			<XField name="adc4" byteoffset="23" length="2" type="uint16"/>
		</XFields>
		<XFilter>
			<XCondAnd>
			
				<!--
					Check if this is a sensor type packet...AMTYPE_MULTIHOP or AMTYPE_XDEBUG
					The Byte offsets defined above assume that there is a multihop header
				/-->
				<XCondOr>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x00"/>
					</XCond>

					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x32"/>
					</XCond>

				</XCondOr>
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="board_id"/>
					<XFilterParam name="fieldvalue" value="0x82"/>
				</XCond>				
			</XCondAnd>
		</XFilter>
		<XDataSinks>
			<XDataSink name="Generic Print Datasink">
				<XDSParam name="printstring" value="MTS101 [sensor data converted to engineering units]:\n   health:     node id=%s		battery:  = %s mv \n   tempurature: =%s degC		light: = %s mv \n   adc2 = %s mv   adc3 = %s mv	adc4 = %s mv "/>
				<XDSParam name="printfields" value="nodeid,voltage,temp,light,adc2,adc3,adc4"/>
			</XDataSink>
			<XDataSink name="Generic Alert Datasink">
				<XDSParam name="voltage" value="[2500,3500]"/>
				<XDSParam name="temp" value="[-5,45]"/>
				<XDSParam name="light" value="[0,3000]"/>
				<XDSParam name="adc2" value="[0,3200]"/>
				<XDSParam name="adc3" value="[0,3200]"/>
				<XDSParam name="adc4" value="[0,3200]"/>
			</XDataSink>
			<XDataSink name="Open Log Datasink">
				<XDSParam name="tablename_1" value="mts101_results"/>
				<XDSParam name="createsql_1" value="CREATE TABLE mts101_results ( result_time timestamp without time zone,epoch integer, nodeid integer, parent integer,voltage integer, temp integer, light integer, adc2 integer, adc3 integer, adc4 integer)"/>				
				<XDSParam name="tablename_2" value="mts101_results_l"/>				
				<XDSParam name="createsql_2" value="CREATE TABLE mts101_results_l ( result_time timestamp without time zone,epoch integer, nodeid integer, parent integer,voltage integer, temp integer, light integer, adc2 integer, adc3 integer, adc4 integer)"/>
				<XDSParam name="rulesql_2" value="CREATE RULE cache_mts101_results AS ON INSERT TO mts101_results DO ( DELETE FROM mts101_results_l WHERE nodeid = NEW.nodeid;INSERT INTO mts101_results_l VALUES (NEW.*); )"/>				
				<XDSParam name="insertsql_2" value="INSERT into mts101_results (result_time,nodeid,voltage,temp,light,adc2,adc3,adc4) values (now(),%i,%i,%i,%i,%i,%i,%i)"/>
				<XDSParam name="insertfields_2" value="nodeid,voltage,temp,light,adc2,adc3,adc4"/>
			</XDataSink>
		</XDataSinks>
	</XFieldExtractor>

</XServeConfig>

=== lafirachid/xmeshadc/tools/xserve/bin/configxml/surge_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE XServeConfig SYSTEM "./xserve_config.dtd">
<XServeConfig>
	<XFieldExtractor name="Surge Config XML" order="1">
		<XFields>
			<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
			<XField name="nodeid" byteoffset="7" length="2" type="uint16" specialtype="nodeid"/>
			<XField name="parent" byteoffset="15" length="2" type="uint16" specialtype="parentid"/>
			<XBitField name="vref" byteoffset="17" length="4" type="uint32" mask="0xFF800000" shift="23">
				<XConversion function="(1252352/x)" returntype="uint16">
					<XConvParam variablename="x" fieldname="vref" type="float"/>
				</XConversion>
			</XBitField>
			<XBitField name="epoch" byteoffset="17" length="4" type="uint32" mask="0x007FFFFF" shift="0"/>
			<XField name="light" byteoffset="21" length="1" type="uint8">
				<XConversion function="((y * (1252352/x) / 1023)* 4)" returntype="uint16">
					<XConvParam variablename="x" fieldname="vref" type="float"/>
					<XConvParam variablename="y" fieldname="light" type="uint8"/>
				</XConversion>
			</XField>
			<XField name="thermistor" byteoffset="22" length="1" type="uint8">
				<XConversion function="((1/(.001307050 + 0.000214381 * log( (10000 * (1023-(x*4)))/(x*4)   ) + 0.000000093 * (log( (10000 * (1023-(x*4)))/(x*4) )^3))) - 273.15)" returntype="float">
					<XConvParam variablename="x" fieldname="thermistor" type="uint16"/>					
				</XConversion>			
			</XField>
			<XField name="magX" byteoffset="23" length="1" type="uint8">
				<XConversion function="(x*4) / (1.023*2.262*3.2)" returntype="float">
					<XConvParam variablename="x" fieldname="magX" type="uint16"/>					
				</XConversion>
			</XField>
			<XField name="magY" byteoffset="24" length="1" type="uint8">
				<XConversion function="(x*4) / (1.023*2.262*3.2)" returntype="float">
					<XConvParam variablename="x" fieldname="magY" type="uint16"/>					
				</XConversion>
			</XField>
			<XField name="accelX" byteoffset="25" length="1" type="uint8">
				<XConversion function="1000.0 * (1.0 - (500 - (x*4))/((500 - 400)/2))" returntype="float">
					<XConvParam variablename="x" fieldname="accelX" type="uint16"/>					
				</XConversion>
			</XField>
			<XField name="accelY" byteoffset="26" length="1" type="uint8">
				<XConversion function="1000.0 * (1.0 - (500 - (x*4))/((500 - 400)/2))" returntype="float">
					<XConvParam variablename="x" fieldname="accelY" type="uint16"/>					
				</XConversion>
			</XField>
		</XFields>
		<XFilter>
			<XCond name="IsEqual">
				<XFilterParam name="fieldname" value="amtype"/>
				<XFilterParam name="fieldvalue" value="17"/>
			</XCond>
		</XFilter>
		<XDataSinks>
		
			<XDataSink name="Generic Print Datasink">
				<XDSParam name="printstring" value="SURGE [sensor data converted to engineering units]:\n   health:  node id=%s  parent=%s  seq_no=%s\n   battery     = %s mv\n   temperature = %s degC\n   light:      = %s ADC mv\n   AccelX:     = %s g,         AccelY: = %s g\n   MagX:       = %s mgauss, MagY:   = %s mgauss "/>
				<XDSParam name="printfields" value="nodeid,parent,epoch,vref,thermistor,light,accelX,accelY,magX,magY"/>
			</XDataSink>

			<XDataSink name="Generic File Datasink">				
				<XDSParam name="rawfilename" value="/opt/tinyos-1.x/raw_surge_data.txt"/>
				<XDSParam name="parsedfilename" value="/opt/tinyos-1.x/parsed_surge_data.txt"/>
				<XDSParam name="convertedfilename" value="/opt/tinyos-1.x/converted_surge_data.txt"/>				
				<XDSParam name="delim" value=","/>
				<XDSParam name="header" value="yes"/>
			</XDataSink>
			<XDataSink name="Open Log Datasink">
				<XDSParam name="tablename_1" value="surge_results"/>
				<XDSParam name="createsql_1" value="CREATE TABLE surge_results ( result_time timestamp without time zone,nodeid integer,parent integer,epoch integer,voltage integer,temp integer,light integer,accel_x integer,accel_y integer,mag_x integer,mag_y integer)"/>				
				<XDSParam name="tablename_2" value="surge_results_l"/>				
				<XDSParam name="createsql_2" value="CREATE TABLE surge_results ( result_time timestamp without time zone,nodeid integer,parent integer,epoch integer,voltage integer,temp integer,light integer,accel_x integer,accel_y integer,mag_x integer,mag_y integer)"/>
				<XDSParam name="rulesql_2" value="CREATE RULE cache_surge_results AS ON INSERT TO surge_results DO ( DELETE FROM surge_results_l WHERE nodeid = NEW.nodeid;INSERT INTO surge_results_l VALUES (NEW.*); )"/>				
				<XDSParam name="insertsql_2" value="INSERT into surge_results (result_time,nodeid,parent,epoch,voltage,temp,light,accel_x,accel_y,mag_x,mag_y) values (now(),%i,%i,%i,%i,%i,%i,%i,%i,%i,%i)"/>
				<XDSParam name="insertfields_2" value="nodeid,parent,epoch,vref,thermistor,light,accelX,accelY,magX,magY"/>
			</XDataSink>
			
		</XDataSinks>
	</XFieldExtractor>
</XServeConfig>

=== lafirachid/xmeshadc/tools/xserve/bin/configxml/mep510_sensor_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE XServeConfig SYSTEM "./xserve_config.dtd">
<XServeConfig>
	<XFieldExtractor name="XMEP510 XSENSOR Config XML" order="3">
		<XFields>
			<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
			<XField name="nodeid" byteoffset="7" length="2" type="uint16" specialtype="nodeid"/>
			<!--
			<XField name="parent" byteoffset="14" length="2" type="uint16" specialtype="parentid"/>
			/-->
			<XField name="group" byteoffset="3" length="1" type="uint8"/>
			<XField name="board_id" byteoffset="5" length="1" type="uint8" specialtype="boardid"/>
			<XField name="packet_id" byteoffset="6" length="1" type="uint8"/>
			<XField name="seqno" byteoffset="8" length="2" type="uint16"/>
			<XField name="voltval" byteoffset="9" length="2" type="uint16">
				<XConversion function="(1251100/x)" returntype="uint16">
					<XConvParam variablename="x" fieldname="voltval" type="float"/>
				</XConversion>
			</XField>
			<XUnionField name="voltage" type="uint16" optor="lshift" leftname="voltval" rightname="0"/>

			<XField name="tempR" byteoffset="11" length="2" type="uint16">
				<XConversion function="(10000*x / (1023-x))" returntype="uint16">
					<XConvParam variablename="x" fieldname="tempR" type="float"/>					
				</XConversion>			
			</XField>
			<XField name="thermister" byteoffset="11" length="2" type="uint16">
				<XConversion function="((1/(.001307050 + 0.000214381 * log( (10000 *x/ (1023-x))   ) + 0.000000093 * (log( (10000 *x/ (1023-x)) )^3))) - 273.15)" returntype="float">
					<XConvParam variablename="x" fieldname="thermister" type="float"/>					
				</XConversion>			
			</XField>
			<XField name="humidity" byteoffset="13" length="2" type="uint16">
				<XConversion function="(-38.4 + 0.0098*y - 25.0)*(0.01 + 0.00008 * x) - 4.0 + 0.0405 * x - 0.0000028 * x * x" returntype="float">
					<XConvParam variablename="x" fieldname="humidity" type="float"/>					
					<XConvParam variablename="y" fieldname="temp_hum" type="float"/>				
				</XConversion>			
			</XField>
			<XField name="temp_hum" byteoffset="15" length="2" type="uint16">
				<XConversion function="(-38.4 + 0.0098*x)" returntype="float">
					<XConvParam variablename="x" fieldname="temp_hum" type="float"/>					
				</XConversion>			
			</XField>
		</XFields>
		<XFilter>
			<XCondAnd>
			
				<!--
					Check if this is a sensor type packet...AMTYPE_MULTIHOP or AMTYPE_XDEBUG
					The Byte offsets defined above assume that there is a multihop header
				/-->
				<XCondOr>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x00"/>
					</XCond>

					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x32"/>
					</XCond>
				</XCondOr>
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="board_id"/>
					<XFilterParam name="fieldvalue" value="0x04"/>
				</XCond>				
			</XCondAnd>
		</XFilter>
		<XDataSinks>
			<XDataSink name="Generic Print Datasink">
				<XDSParam name="printstring" value="MEP510 [sensor data converted to engineering units]:\n   health:     node id=%s \n   battery: =%s mv \n   thermistor: resistance=%s ohms, tempurature=%s C\n   temperature: =%s degC \n   humidity: =%s%%"/>
				<XDSParam name="printfields" value="nodeid,voltval,tempR,thermister,temp_hum,humidity"/>
			</XDataSink>
			<XDataSink name="Open Log Datasink">
				<XDSParam name="tablename_1" value="mep_results"/>
				<XDSParam name="createsql_1" value="CREATE TABLE mep_results ( result_time timestamp without time zone,epoch integer,nodeid integer,parent integer,voltage integer,thermister integer,humidity integer,temp_hum integer,inthum integer,inttemp integer,par_bottom integer,tsr_bottom integer,par_top integer,tsr_top integer,temp_pr integer,pressure integer,board_id integer)"/>				
				<XDSParam name="tablename_2" value="mep_results_l"/>				
				<XDSParam name="createsql_2" value="CREATE TABLE mep_results_l ( result_time timestamp without time zone,epoch integer,nodeid integer,parent integer,voltage integer,thermister integer,humidity integer,temp_hum integer,inthum integer,inttemp integer,par_bottom integer,tsr_bottom integer,par_top integer,tsr_top integer,temp_pr integer,pressure integer,board_id integer)"/>
				<XDSParam name="rulesql_2" value="CREATE RULE cache_mep_results AS ON INSERT TO mep_results DO ( DELETE FROM mep_results_l WHERE nodeid = NEW.nodeid;INSERT INTO mep_results_l VALUES (NEW.*); )"/>				
				<XDSParam name="insertsql_2" value="INSERT into mep_results (result_time,nodeid,epoch,voltage,thermister,humidity,temp_hum,board_id) values (now(),%i,%i,%i,%i,%i,%i,%i)"/>
				<XDSParam name="insertfields_2" value="nodeid,seqno,voltage,thermister,humidity,temp_hum,board_id"/>
			</XDataSink>
			<XDataSink name="Generic Alert Datasink">
				<XDSParam name="voltval" value="[2500,3500]"/>
				<XDSParam name="thermister" value="[-5,45]"/>
				<XDSParam name="humidity" value="[0,100]"/>
				<XDSParam name="temp_hum" value="[-5,45]"/>
			</XDataSink>
		</XDataSinks>
	</XFieldExtractor>

</XServeConfig>

=== lafirachid/xmeshadc/trunk/tools/xserve/bin/configxml/heartbeat_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE XServeConfig SYSTEM "./xserve_config.dtd">
<XServeConfig>
	<XFieldExtractor name="Heartbeat Config XML" order="1">
		<XFields>
			<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
		</XFields>
		<XFilter>
			<XCond name="IsEqual">
				<XFilterParam name="fieldname" value="amtype"/>
				<XFilterParam name="fieldvalue" value="253"/>
			</XCond>
		</XFilter>
		<XDataSinks/>
	</XFieldExtractor>
</XServeConfig>
