=== lafirachid/xmeshadc/trunk/tools/xserve/bin/configxml/xserve_config.dtd
<!ELEMENT XServeConfig (XFieldExtractor)+>

<!ELEMENT XFieldExtractor (XFields,XFilter,XDataSinks)>
<!ATTLIST XFieldExtractor name CDATA #REQUIRED>
<!ATTLIST XFieldExtractor order CDATA #REQUIRED>


<!ELEMENT XFields (XField|XBitField|XUnionField)+>
<!ELEMENT XField (XConversion)?>
<!ATTLIST XField name CDATA #REQUIRED>
<!ATTLIST XField byteoffset CDATA #REQUIRED>
<!ATTLIST XField length CDATA #REQUIRED>
<!ATTLIST XField type (byte|char|short|int|long|uint8|uint16|uint32|uint64|string|raw|float|double) #REQUIRED>
<!ATTLIST XField specialtype (nodeid|parentid|boardid) #IMPLIED>

<!ELEMENT XConversion (XConvParam)*>
<!ATTLIST XConversion function CDATA #REQUIRED>
<!ATTLIST XConversion returntype (byte|char|short|int|long|uint8|uint16|uint32|uint64|string|raw|float|double) #REQUIRED>

<!ELEMENT XConvParam EMPTY>
<!ATTLIST XConvParam variablename CDATA #REQUIRED>
<!ATTLIST XConvParam fieldname CDATA #REQUIRED>
<!ATTLIST XConvParam type (byte|char|short|int|long|uint8|uint16|uint32|uint64|string|raw|float|double) #REQUIRED>



<!ELEMENT XBitField (XConversion)?>
<!ATTLIST XBitField name CDATA #REQUIRED>
<!ATTLIST XBitField byteoffset CDATA #REQUIRED>
<!ATTLIST XBitField length CDATA #REQUIRED>
<!ATTLIST XBitField type (byte|char|short|int|long|uint8|uint16|uint32|uint64|string|raw|float|double) #REQUIRED>
<!ATTLIST XBitField specialtype (nodeid|parentid|boardid) #IMPLIED>
<!ATTLIST XBitField mask CDATA #REQUIRED>
<!ATTLIST XBitField shift CDATA #REQUIRED>

<!ELEMENT XUnionField EMPTY>
<!ATTLIST XUnionField name CDATA #REQUIRED>
<!ATTLIST XUnionField type (byte|char|short|int|long|uint8|uint16|uint32|uint64|string|raw|float|double) #REQUIRED>
<!ATTLIST XUnionField optor CDATA #REQUIRED>
<!ATTLIST XUnionField specialtype (nodeid|parentid|boardid) #IMPLIED>
<!ATTLIST XUnionField leftname CDATA #REQUIRED>
<!ATTLIST XUnionField rightname CDATA #REQUIRED>

<!ELEMENT XDataSinks (XDataSink)*>
<!ELEMENT XDataSink (XDSParam)+>
<!ATTLIST XDataSink name CDATA #REQUIRED>

<!ELEMENT XDSParam EMPTY>
<!ATTLIST XDSParam name CDATA #REQUIRED>
<!ATTLIST XDSParam value CDATA #REQUIRED>


<!ELEMENT XFilter (XCondAnd|XCondOr|XCondNot|XCond)+>
<!ELEMENT XCondAnd (XCondAnd|XCondOr|XCondNot|XCond)+>
<!ELEMENT XCondOr (XCondAnd|XCondOr|XCondNot|XCond)+>
<!ELEMENT XCondNot (XCondAnd|XCondOr|XCondNot|XCond)>
<!ELEMENT XCond (XFilterParam)*>
<!ATTLIST XCond name CDATA #REQUIRED>

<!ELEMENT XFilterParam EMPTY>
<!ATTLIST XFilterParam name CDATA #REQUIRED>
<!ATTLIST XFilterParam value CDATA #REQUIRED>

=== lafirachid/xmeshadc/tools/xserve/bin/configxml/mda320_mesh_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE XServeConfig SYSTEM "./xserve_config.dtd">
<XServeConfig>
	<XFieldExtractor name="XMDA320 Multihop PK6 Config XML" order="3">
		<XFields>
			<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
			<XField name="nodeid" byteoffset="7" length="2" type="uint16" specialtype="nodeid"/>
			<XField name="parent" byteoffset="14" length="2" type="uint16" specialtype="parentid"/>
			<XField name="group" byteoffset="3" length="1" type="uint8"/>
			<XField name="socketid" byteoffset="11" length="1" type="uint8"/>
			<XField name="board_id" byteoffset="12" length="1" type="uint8" specialtype="boardid"/>
			<XField name="packet_id" byteoffset="13" length="1" type="uint8"/>
			<XField name="voltage" byteoffset="16" length="2" type="uint16">
				<XConversion function="(1252352/x)" returntype="uint16">
					<XConvParam variablename="x" fieldname="voltage" type="float"/>
				</XConversion>
			</XField>
			<XField name="adc0" byteoffset="18" length="2" type="uint16">
				<XConversion function="(625*x/16384)" returntype="uint16">
					<XConvParam variablename="x" fieldname="adc0" type="uint16"/>
				</XConversion>
			</XField>
			<XField name="adc1" byteoffset="20" length="2" type="uint16">
				<XConversion function="(625*x/16384)" returntype="uint16">
					<XConvParam variablename="x" fieldname="adc1" type="uint16"/>
				</XConversion>
			</XField>
			<XField name="adc2" byteoffset="22" length="2" type="uint16">
				<XConversion function="(625*x/16384)" returntype="uint16">
					<XConvParam variablename="x" fieldname="adc2" type="uint16"/>
				</XConversion>
			</XField>
			<XField name="adc3" byteoffset="24" length="2" type="uint16">
				<XConversion function="(625*x/16384)" returntype="uint16">
					<XConvParam variablename="x" fieldname="adc3" type="uint16"/>
				</XConversion>
			</XField>
			<XField name="digi0" byteoffset="26" length="2" type="uint16"/>
			<XField name="digi1" byteoffset="28" length="2" type="uint16"/>
			<XField name="digi2" byteoffset="30" length="2" type="uint16"/>
			<XField name="digi3" byteoffset="32" length="2" type="uint16"/>
		</XFields>
		<XFilter>
			<XCondAnd>
			
				<!--
					Check if this is a sensor type packet...AMTYPE_MULTIHOP or AMTYPE_XDEBUG
					The Byte offsets defined above assume that there is a multihop header
				/-->
				<XCondOr>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x31"/>
					</XCond>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x33"/>
					</XCond>
					<XCondAnd>
						<XCondOr>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="socketid"/>
								<XFilterParam name="fieldvalue" value="0x31"/>
							</XCond>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="socketid"/>
								<XFilterParam name="fieldvalue" value="0x33"/>
							</XCond>
						</XCondOr>
						<XCondOr>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="amtype"/>
								<XFilterParam name="fieldvalue" value="0x0B"/>
							</XCond>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="amtype"/>
								<XFilterParam name="fieldvalue" value="0x0D"/>
							</XCond>
						</XCondOr>
					
					</XCondAnd>
				</XCondOr>
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="board_id"/>
					<XFilterParam name="fieldvalue" value="0x90"/>
				</XCond>				
				<XCondOr>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="packet_id"/>
						<XFilterParam name="fieldvalue" value="0x86"/>
					</XCond>

					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="packet_id"/>
						<XFilterParam name="fieldvalue" value="0x06"/>
					</XCond>
				</XCondOr>
			</XCondAnd>
		</XFilter>
		<XDataSinks>
			<XDataSink name="Generic Print Datasink">
				<XDSParam name="printstring" value="MDA320 [sensor data converted to engineering units]:\n   health:     node id=%s parent=%s battery=%s mV\n   adc chan 0: voltage=%s mV\n   adc chan 1: voltage=%s mV\n   adc chan 2: voltage=%s mV\n   adc chan 3: voltage=%s mV\n   dig chan 0: =%s \n   dig chan 1: =%s \n   dig chan 2: =%s \n   dig chan 3: =%s "/>
				<XDSParam name="printfields" value="nodeid,parent,voltage,adc0,adc1,adc2,adc3,digi0,digi1,digi2,digi3"/>
			</XDataSink>
			<XDataSink name="Open Log Datasink">
				<XDSParam name="tablename_1" value="mda320_results"/>
				<XDSParam name="createsql_1" value="CREATE TABLE mda320_results ( result_time timestamp without time zone,nodeid integer, parent integer,adc0 integer, adc1 integer, adc2 integer, adc3 integer,digi0 integer,digi1 integer,digi2 integer,digi3 integer,voltage integer)"/>				
				<XDSParam name="tablename_2" value="mda320_results_l"/>				
				<XDSParam name="createsql_2" value="CREATE TABLE mda320_results_l ( result_time timestamp without time zone,nodeid integer, parent integer,adc0 integer, adc1 integer, adc2 integer, adc3 integer,digi0 integer,digi1 integer,digi2 integer,digi3 integer,voltage integer)"/>
				<XDSParam name="rulesql_2" value="CREATE RULE cache_mda320_results AS ON INSERT TO mda320_results DO ( DELETE FROM mda320_results_l WHERE nodeid = NEW.nodeid;INSERT INTO mda320_results_l VALUES (NEW.*); )"/>				
				<XDSParam name="insertsql_2" value="INSERT into mda320_results (result_time,nodeid,parent,voltage,adc0,adc1,adc2,adc3,digi0, digi1, digi2, digi3) values (now(),%i,%i,%i,%i,%i,%i,%i,%i,%i,%i,%i)"/>
				<XDSParam name="insertfields_2" value="nodeid,parent,voltage,adc0,adc1,adc2,adc3,digi0,digi1,digi2,digi3"/>
			</XDataSink>
			<XDataSink name="Generic test Datasink">
				<XDSParam name="voltage" value="[2500,3500]"/>
				<XDSParam name="adc0" value="[0,2500]"/>
				<XDSParam name="adc1" value="[0,2500]"/>
				<XDSParam name="adc2" value="[0,2500]"/>
				<XDSParam name="adc3" value="[0,2500]"/>
			</XDataSink>
		</XDataSinks>
	</XFieldExtractor>

</XServeConfig>

=== lafirachid/xmeshadc/tools/xserve/bin/configxml/xcommand_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE XServeConfig SYSTEM "./xserve_config.dtd">
<XServeConfig>
	<XFieldExtractor name="XCommand Config XML" order="1">
		<XFields>
			<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
			<XField name="sourceaddr" byteoffset="5" length="2" type="uint16"/>
			<XField name="originaddr" byteoffset="7" length="2" type="uint16"/>
			<XField name="socketid" byteoffset="11" length="1" type="uint8"/>
			<XField name="boardid" byteoffset="12" length="1" type="uint8"/>
			<XField name="packetid" byteoffset="13" length="1" type="uint8"/>
			<XField name="nodeid" byteoffset="14" length="2" type="uint16"/>
			<XField name="responsecode" byteoffset="16" length="1" type="uint8"/>
			<XField name="cmdkey" byteoffset="17" length="1" type="uint8"/>						
		</XFields>
		<XFilter>
			<XCondAnd>				
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="socketid"/>
					<XFilterParam name="fieldvalue" value="0x30"/>
				</XCond>			
				<XCondOr>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="boardid"/>
						<XFilterParam name="fieldvalue" value="0x60"/>
					</XCond>			
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="boardid"/>
						<XFilterParam name="fieldvalue" value="0x61"/>
					</XCond>			
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="boardid"/>
						<XFilterParam name="fieldvalue" value="0x62"/>
					</XCond>			
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="boardid"/>
						<XFilterParam name="fieldvalue" value="0x69"/>
					</XCond>			
					
				</XCondOr>
			</XCondAnd>
		</XFilter>
		<XDataSinks/>
	</XFieldExtractor>
</XServeConfig>

=== lafirachid/xmeshadc/tools/xserve/bin/configxml/health_mesh_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE XServeConfig SYSTEM "./xserve_config.dtd">
<XServeConfig>
	<XFieldExtractor name="Node Health XML" order="3">
		<XFields>
			<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
			<XField name="sourceaddr" byteoffset="5" length="2" type="uint16"/>
			<XField name="nodeid" byteoffset="7" length="2" type="uint16"/>
			<XField name="socketid" byteoffset="11" length="1" type="uint8"/>
			<XBitField name="old_type" byteoffset="12" length="1" type="uint8" mask="0xF0" shift="4"/>
			<XBitField name="node_count" byteoffset="12" length="1" type="uint8" mask="0x0F" shift="0"/>
			<XField name="version" byteoffset="13" length="1" type="uint8"/>
			<XField name="type" byteoffset="14" length="1" type="uint8"/>
			<XField name="health_pkts" byteoffset="15" length="2" type="uint16"/>
			<XField name="node_pkts" byteoffset="17" length="2" type="uint16"/>
			<XField name="forwarded" byteoffset="19" length="2" type="uint16"/>
			<XField name="dropped" byteoffset="21" length="2" type="uint16"/>
			<XField name="retries" byteoffset="23" length="2" type="uint16"/>
			<XField name="battery" byteoffset="25" length="1" type="uint8">
				<XConversion function="x/10.0" returntype="float">
					<XConvParam variablename="x" fieldname="battery" type="float"/>
				</XConversion>
			</XField>
			<XField name="power_sum" byteoffset="26" length="2" type="uint16"/>
			<XField name="board_id" byteoffset="28" length="1" type="uint8"/>
			<XField name="parent" byteoffset="29" length="2" type="uint16"/>			
			<XBitField name="quality_tx" byteoffset="31" length="1" type="uint8" mask="0x0F" shift="0"/>
			<XBitField name="quality_rx" byteoffset="31" length="1" type="uint8" mask="0xFF" shift="4"/>
			<XField name="path_cost" byteoffset="32" length="1" type="uint8"/>			
			<XField name="parent_rssi" byteoffset="33" length="1" type="uint8"/>			
		</XFields>
		<XFilter>
			<XCondAnd>				
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="socketid"/>
					<XFilterParam name="fieldvalue" value="0x03"/>
				</XCond>				
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="old_type"/>
					<XFilterParam name="fieldvalue" value="0x0F"/>
				</XCond>				
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="type"/>
					<XFilterParam name="fieldvalue" value="1"/>
				</XCond>				
			</XCondAnd>
		</XFilter>
		<XDataSinks>
			<XDataSink name="Generic Print Datasink">
				<XDSParam name="printstring" value="HEALTH Stats:\n	Sender-id=%s[FWD by %s]\n  app_pkt=%s, forw_pkt=%s, drop_pkt=%s, retransmits=%s\n   battery=%s, power_sum=%s\n 	Parent: %s, Link Quality %s,%s, Path Cost %s, RSSI %s"/>
				<XDSParam name="printfields" value="nodeid,sourceaddr,apppkts,fwdpkts,drpppkts,retranspkts,battery,power_sum,parent,quality_rx,quality_tx,path_cost,parent_rssi"/>
			</XDataSink>
			<XDataSink name="Open Log Datasink">
				<XDSParam name="tablename_1" value="node_health_l"/>
				<XDSParam name="createsql_1" value="CREATE TABLE node_health_l ( result_time timestamp without time zone,epoch integer, nodeid integer, health_pkts integer, node_pkts integer, forwarded integer, dropped integer, retries integer, battery integer, power_sum integer,board_id integer, parent integer, quality_tx integer, quality_rx integer, path_cost integer, parent_rssi integer)"/>				
				<XDSParam name="tablename_2" value="node_health"/>
				<XDSParam name="createsql_2" value="CREATE TABLE node_health ( result_time timestamp without time zone,epoch integer, nodeid integer, health_pkts integer, node_pkts integer, forwarded integer, dropped integer, retries integer, battery integer, power_sum integer, board_id integer, parent integer, quality_tx integer, quality_rx integer, path_cost integer, parent_rssi integer); DELETE FROM task_query_log WHERE query_id=3 and query_type='MOTEVIEW_1_0'; INSERT INTO task_query_log (query_id, table_name, query_type) VALUES (3, 'node_health', 'MOTEVIEW_1_0');"/>				
				<XDSParam name="rulesql_2" value="CREATE RULE cache_node_health AS ON INSERT TO node_health DO ( DELETE FROM node_health_l WHERE nodeid = NEW.nodeid;INSERT INTO node_health_l VALUES (NEW.*); )"/>				
				<XDSParam name="insertsql_2" value="INSERT into node_health (result_time,nodeid,health_pkts,node_pkts,forwarded,dropped,retries,battery,power_sum,board_id,parent,quality_tx,quality_rx,path_cost,parent_rssi) values (now(),%i,%i,%i,%i,%i,%i,%i,%i,%i,%i,%i,%i,%i,%i)"/>
				<XDSParam name="insertfields_2" value="nodeid,health_pkts,node_pkts,forwarded,dropped,retries,battery,power_sum,board_id,parent,quality_rx,quality_tx,path_cost,parent_rssi"/>
			</XDataSink>
		</XDataSinks>
	</XFieldExtractor>




<XFieldExtractor name="Neighbor Health Mesh XML" order="3">
		<XFields>
			<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
			<XField name="sourceaddr" byteoffset="5" length="2" type="uint16"/>
			<XField name="nodeid" byteoffset="7" length="2" type="uint16"/>
			<XField name="socketid" byteoffset="11" length="1" type="uint8"/>
			<XBitField name="old_type" byteoffset="12" length="1" type="uint8" mask="0xF0" shift="4"/>
			<XBitField name="node_count" byteoffset="12" length="1" type="uint8" mask="0x0F" shift="0"/>
			<XField name="version" byteoffset="13" length="1" type="uint8"/>
			<XField name="type" byteoffset="14" length="1" type="uint8"/>
			
			<XField name="neighborid1" byteoffset="15" length="2" type="uint16"/>			
			<XBitField name="rquality1" byteoffset="17" length="1" type="uint8" mask="0x0F" shift="0"/>
			<XBitField name="lquality1" byteoffset="17" length="1" type="uint8" mask="0xFF" shift="4"/>
			<XField name="pathcost1" byteoffset="18" length="1" type="uint8"/>
			<XField name="rssi1" byteoffset="19" length="1" type="uint8"/>

			<XField name="neighborid2" byteoffset="20" length="2" type="uint16"/>			
			<XBitField name="rquality2" byteoffset="22" length="1" type="uint8" mask="0x0F" shift="0"/>
			<XBitField name="lquality2" byteoffset="22" length="1" type="uint8" mask="0xFF" shift="4"/>
			<XField name="pathcost2" byteoffset="23" length="1" type="uint8"/>
			<XField name="rssi2" byteoffset="24" length="1" type="uint8"/>

			<XField name="neighborid3" byteoffset="25" length="2" type="uint16"/>			
			<XBitField name="rquality3" byteoffset="27" length="1" type="uint8" mask="0x0F" shift="0"/>
			<XBitField name="lquality3" byteoffset="27" length="1" type="uint8" mask="0xFF" shift="4"/>
			<XField name="pathcost3" byteoffset="28" length="1" type="uint8"/>
			<XField name="rssi3" byteoffset="29" length="1" type="uint8"/>

			<XField name="neighborid4" byteoffset="30" length="2" type="uint16"/>			
			<XBitField name="rquality4" byteoffset="32" length="1" type="uint8" mask="0x0F" shift="0"/>
			<XBitField name="lquality4" byteoffset="32" length="1" type="uint8" mask="0xFF" shift="4"/>
			<XField name="pathcost4" byteoffset="33" length="1" type="uint8"/>
			<XField name="rssi4" byteoffset="34" length="1" type="uint8"/>

			<XField name="neighborid5" byteoffset="35" length="2" type="uint16"/>			
			<XBitField name="rquality5" byteoffset="37" length="1" type="uint8" mask="0x0F" shift="0"/>
			<XBitField name="lquality5" byteoffset="37" length="1" type="uint8" mask="0xFF" shift="4"/>
			<XField name="pathcost5" byteoffset="38" length="1" type="uint8"/>
			<XField name="rssi5" byteoffset="39" length="1" type="uint8"/>
		</XFields>
		<XFilter>
			<XCondAnd>				
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="socketid"/>
					<XFilterParam name="fieldvalue" value="0x03"/>
				</XCond>				
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="old_type"/>
					<XFilterParam name="fieldvalue" value="0x0F"/>
				</XCond>				
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="type"/>
					<XFilterParam name="fieldvalue" value="2"/>
				</XCond>				
			</XCondAnd>
		</XFilter>
		<XDataSinks>
			<XDataSink name="Generic Print Datasink">
				<XDSParam name="printstring" value="Neighborhood INFO[Sender-ID %s]: \n Neighbor-ID=%s, Quality=%s,%s, Path Cost=%s, RSSI=%s \n Neighbor-ID=%s, Quality=%s,%s, Path Cost=%s, RSSI=%s \n Neighbor-ID=%s, Quality=%s,%s, Path Cost=%s, RSSI=%s \n Neighbor-ID=%s, Quality=%s,%s, Path Cost=%s, RSSI=%s \n Neighbor-ID=%s, Quality=%s,%s, Path Cost=%s, RSSI=%s"/>
				<XDSParam name="printfields" value="nodeid,neighborid1,lquality1,rquality1,pathcost1,rssi1,neighborid2,lquality2,rquality2,pathcost2,rssi2,neighborid3,lquality3,rquality3,pathcost3,rssi3,neighborid4,lquality4,rquality4,pathcost4,rssi4,neighborid5,lquality5,rquality5,pathcost5,rssi5"/>
			</XDataSink>
		</XDataSinks>
	</XFieldExtractor>




</XServeConfig>

=== lafirachid/xmeshadc/trunk/tools/xserve/bin/configxml/xjoin_mesh_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE XServeConfig SYSTEM "./xserve_config.dtd">
<XServeConfig>
	<XFieldExtractor name="XJoin Mesh XML" order="3">
		<XFields>
			<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
			<XField name="socketid" byteoffset="11" length="1" type="uint8"/>
			<XField name="msgtype" byteoffset="12" length="1" type="uint8"/>
			<XField name="uid" byteoffset="13" length="8" type="raw"/>			
		</XFields>
		<XFilter>
			<XCondAnd>
			<XCond name="IsEqual">
				<XFilterParam name="fieldname" value="socketid"/>
				<XFilterParam name="fieldvalue" value="0x96"/>
			</XCond>
			<XCond name="IsEqual">
				<XFilterParam name="fieldname" value="msgtype"/>
				<XFilterParam name="fieldvalue" value="0"/>
			</XCond>
			</XCondAnd>
		</XFilter>
		<XDataSinks>
			<XDataSink name="Generic Print Datasink">
				<XDSParam name="printstring" value="XJOIN: UniqueId = [%s]"/>
				<XDSParam name="printfields" value="uid"/>
			</XDataSink>
		</XDataSinks>
	</XFieldExtractor>
</XServeConfig>

=== lafirachid/xmeshadc/tools/xserve/bin/configxml/mda100_mesh_config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE XServeConfig SYSTEM "./xserve_config.dtd">
<XServeConfig>
	<XFieldExtractor name="XMDA100 Multihop Config XML" order="3">
		<XFields>
			<XField name="amtype" byteoffset="2" length="1" type="uint8"/>
			<XField name="nodeid" byteoffset="7" length="2" type="uint16" specialtype="nodeid"/>
			<XField name="parent" byteoffset="14" length="2" type="uint16" specialtype="parentid"/>
			<XField name="group" byteoffset="3" length="1" type="uint8"/>
			<XField name="socketid" byteoffset="11" length="1" type="uint8"/>
			<XField name="board_id" byteoffset="12" length="1" type="uint8" specialtype="boardid"/>
			<XField name="packet_id" byteoffset="13" length="1" type="uint8"/>
			<XField name="voltage" byteoffset="16" length="2" type="uint16">
				<XConversion function="(1252352/x)" returntype="uint16">
					<XConvParam variablename="x" fieldname="voltage" type="float"/>
				</XConversion>
			</XField>
			<XField name="temp" byteoffset="18" length="2" type="uint16">
				<XConversion function="((1/(0.001307050 + 0.000214381 * log( 10000*(1023-x)/x) + 0.000000093 * (log( 10000*(1023-x)/x )^3))) - 273.15)" returntype="float">
					<XConvParam variablename="x" fieldname="temp" type="uint16"/>					
				</XConversion>			
			</XField>
			<XField name="light" byteoffset="20" length="2" type="uint16">
				<XConversion function="(y * (1252352/x) / 1023)" returntype="uint16">
					<XConvParam variablename="x" fieldname="voltage" type="float"/>
					<XConvParam variablename="y" fieldname="light" type="uint16"/>
				</XConversion>
			</XField>
			<XField name="adc2" byteoffset="22" length="2" type="uint16">
				<XConversion function="(x * (1252352/y) / 1023)" returntype="uint16">
					<XConvParam variablename="x" fieldname="adc2" type="uint16"/>
					<XConvParam variablename="y" fieldname="voltage" type="float"/>
				</XConversion>
			</XField>
			<XField name="adc3" byteoffset="24" length="2" type="uint16">
				<XConversion function="(x * (1252352/y) / 1023)" returntype="uint16">
					<XConvParam variablename="x" fieldname="adc3" type="uint16"/>
					<XConvParam variablename="y" fieldname="voltage" type="float"/>
				</XConversion>
			</XField>
			<XField name="adc4" byteoffset="26" length="2" type="uint16">
				<XConversion function="(x * (1252352/y) / 1023)" returntype="uint16">
					<XConvParam variablename="x" fieldname="adc4" type="uint16"/>
					<XConvParam variablename="y" fieldname="voltage" type="float"/>
				</XConversion>
			</XField>
			<XField name="adc5" byteoffset="28" length="2" type="uint16">
				<XConversion function="(x * (1252352/y) / 1023)" returntype="uint16">
					<XConvParam variablename="x" fieldname="adc5" type="uint16"/>
					<XConvParam variablename="y" fieldname="voltage" type="float"/>
				</XConversion>
			</XField>
			<XField name="adc6" byteoffset="30" length="2" type="uint16">
				<XConversion function="(x * (1252352/y) / 1023)" returntype="uint16">
					<XConvParam variablename="x" fieldname="adc6" type="uint16"/>
					<XConvParam variablename="y" fieldname="voltage" type="float"/>
				</XConversion>
			</XField>
		</XFields>
		<XFilter>
			<XCondAnd>
			
				<!--
					Check if this is a sensor type packet...AMTYPE_MULTIHOP or AMTYPE_XDEBUG
					The Byte offsets defined above assume that there is a multihop header
				/-->
				<XCondOr>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x31"/>
					</XCond>
					<XCond name="IsEqual">
						<XFilterParam name="fieldname" value="amtype"/>
						<XFilterParam name="fieldvalue" value="0x33"/>
					</XCond>
					<XCondAnd>
						<XCondOr>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="socketid"/>
								<XFilterParam name="fieldvalue" value="0x31"/>
							</XCond>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="socketid"/>
								<XFilterParam name="fieldvalue" value="0x33"/>
							</XCond>
						</XCondOr>
						<XCondOr>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="amtype"/>
								<XFilterParam name="fieldvalue" value="0x0B"/>
							</XCond>
							<XCond name="IsEqual">
								<XFilterParam name="fieldname" value="amtype"/>
								<XFilterParam name="fieldvalue" value="0x0D"/>
							</XCond>
						</XCondOr>
					
					</XCondAnd>
				</XCondOr>
				<XCond name="IsEqual">
					<XFilterParam name="fieldname" value="board_id"/>
					<XFilterParam name="fieldvalue" value="0x91"/>
				</XCond>				
			</XCondAnd>
		</XFilter>
		<XDataSinks>
			<XDataSink name="Generic Print Datasink">
				<XDSParam name="printstring" value="MDA100 [sensor data converted to engineering units]:\n   health: node id	= %s	battery:  = %s mv \n	temperature:	= %s degC \n	light:		= %s mv \n	adc chan 2:	= %s mv \n	adc chan 3:	= %s mv	\n	adc chan 4:	= %s mv \n	adc chan 5:	= %s mv	\n	adc chan 6:	= %s mv"/>
				<XDSParam name="printfields" value="nodeid,voltage,temp,light,adc2,adc3,adc4,adc5,adc6"/>
			</XDataSink>
			<XDataSink name="Generic Alert Datasink">
				<XDSParam name="voltage" value="[2500,3500]"/>
				<XDSParam name="temp" value="[-5,45]"/>
				<XDSParam name="light" value="[0,3000]"/>
				<XDSParam name="adc2" value="[0,3200]"/>
				<XDSParam name="adc3" value="[0,3200]"/>
				<XDSParam name="adc4" value="[0,3200]"/>
				<XDSParam name="adc5" value="[0,3200]"/>
				<XDSParam name="adc6" value="[0,3200]"/>
			</XDataSink>
			<XDataSink name="Open Log Datasink">
				<XDSParam name="tablename_1" value="xbw_da100_results"/>
				<XDSParam name="createsql_1" value="CREATE TABLE xbw_da100_results ( result_time timestamp without time zone,epoch integer, nodeid integer, parent integer,voltage integer, temp integer, light integer, adc2 integer,adc3 integer, adc4 integer, adc5 integer, adc6 integer )"/>				
				<XDSParam name="tablename_2" value="xbw_da100_results_l"/>				
				<XDSParam name="createsql_2" value="CREATE TABLE xbw_da100_results_l ( result_time timestamp without time zone,epoch integer, nodeid integer, parent integer,voltage integer, temp integer, light integer, adc2 integer,adc3 integer, adc4 integer, adc5 integer, adc6 integer )"/>
				<XDSParam name="rulesql_2" value="CREATE RULE cache_xbw_da100_results AS ON INSERT TO xbw_da100_results DO ( DELETE FROM xbw_da100_results_l WHERE nodeid = NEW.nodeid;INSERT INTO xbw_da100_results_l VALUES (NEW.*); )"/>				
				<XDSParam name="insertsql_2" value="INSERT into xbw_da100_results (result_time,nodeid,parent,voltage,temp,light,adc2,adc3,adc4,adc5,adc6) values (now(),%i,%i,%i,%i,%i,%i,%i,%i,%i,%i)"/>
				<XDSParam name="insertfields_2" value="nodeid,parent,voltage,temp,light,adc2,adc3,adc4,adc5,adc6"/>
			</XDataSink>
		</XDataSinks>
	</XFieldExtractor>

</XServeConfig>
